DefaultContentLanguage = "fr"
baseurl = "https://www.notkaa.xyz"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
metaDataFormat = "yaml"
publishdir = "public"
pygmentCodeFences = true
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Notkaa"
[Author]
email = "rv@notkaa.xyz"
gitlab = "notkaa"
instagram = "notkaa0"
twitter = "@not_kaa"
vimeo = "notkaa"
youtube = "user/notkaa"
[Params]
comments = false
commit = false
dateFormat = "2 January, 2006"
favicon = "/uploads/favicon.ico"
logo = "/uploads/2021-07-23-avatar.png"
rss = true
subtitle = "mon carnet de notes"
[[menu.main]]
name = "Tags"
url = "tags"
weight = 4
[[menu.main]]
name = "blog"
weight = 1
