DefaultContentLanguage = "fr"
baseurl = "https://www.notkaa.xyz"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
metaDataFormat = "yaml"
publishdir = "public"
pygmentCodeFences = true
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Notkaa"
[Author]
bandcamp = "username"
email = "rv@notkaa.xyz"
github = "username"
gitlab = "notkaa"
instagram = "username"
name = "notkaa"
reddit = "username"
twitter = "@not_kaa"
youtube = "user/username"
[Params]
comments = true
commit = false
dateFormat = "January 2, 2006"
favicon = "img/favicon.ico"
logo = "img/avatar-notkaa.png"
rss = true
subtitle = "carnet de notes"
[[menu.main]]
name = "Tags"
url = "tags"
weight = 6
[[menu.main]]
name = "Code Sample"
parent = "samples"
url = "post/2016-03-08-code-sample"
weight = 7
[[menu.main]]
name = "Math Sample"
parent = "samples"
url = "post/2017-03-05-math-sample"
weight = 3
[[menu.main]]
name = "Big Image Sample"
parent = "samples"
url = "post/2017-03-07-bigimg-sample"
weight = 1
[[menu.main]]
identifier = "samples"
name = "Samples"
weight = 4
[[menu.main]]
name = "Blog"
weight = 2
