DefaultContentLanguage = "fr"
baseurl = "https://www.notkaa.xyz"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
metaDataFormat = "yaml"
publishdir = "public"
pygmentCodeFences = true
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "notkaa"
[Author]
email = "rv@notkaa.xyz"
github = "notkaa"
instagram = "notkaa0"
mastodon = "@Notkaa@mastodon.art"
twitter = "@not_kaa"
vimeo = "notkaa"
youtube = "user/notkaa"
[Params]
comments = false
commit = false
dateFormat = "2 January, 2006"
favicon = "/uploads/favicon.ico"
logo = "/uploads/2021-07-23-avatar.png"
rss = true
subtitle = "mon carnet de notes"

[[menu.main]]
name = "blog"
weight = 1

[[menu.main]]
    name = "qui ?"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "raccourcis"
    name = "raccourcis"
    weight = 2

[[menu.main]]
    parent = "raccourcis"
    name = "photographies"
    url = "/content/page/photographies.md"
    weight = 1

[[menu.main]]
    parent = "raccourcis"
    name = "vidéos"
    url = "/content/page/photographies.md"
    weight = 2

[[menu.main]]
    parent = "raccourcis"
    name = "run"
    url = "https://runalyze.com/athlete/notkaa"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
